### PR TITLE
Expose Redux

### PR DESCRIPTION
**Pull request by FunctionalMetatable**

### CODE REVIEW

**Comment by LankyBox01** [comment]
what the hell is exposing redux supposed to do

**Comment by CST1229** [comment]
> 
> 
> what the hell is exposing redux supposed to do

Basically it allows you to access redux to do events and stuff, like triggering the eyedropper to change the chosen color I think.

**Comment by LankyBox01** [comment]
and what does this pr gonna do
and also how does this help

**Comment by LankyBox01** [comment]
?

**Pull request closed without merging**
